name: Deploy Website

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      # Build and Deploy to GitHub Pages
      - name: Build for GitHub Pages
        env:
          DEPLOY_TARGET: github
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Build and Deploy to Dreamhost
      - name: Setup SSH for Dreamhost
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_SSH_KEY }}

      - name: Add Dreamhost to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H webonwater.com >> ~/.ssh/known_hosts

      - name: Build for Dreamhost
        env:
          DEPLOY_TARGET: dreamhost
        run: npm run build

      - name: Deploy to Dreamhost
        env:
          DREAMHOST_SSH_USER: ${{ secrets.DREAMHOST_SSH_USER }}
        run: npm run deploy:dreamhost

  deploy-github:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-and-deploy
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
